### DISCUSSION TITLE
vcs freeze

### DISCUSSION THREAD

**Discussion by Ryanf55** [MaxandreOgeret/vcstool2#7] [Ideas]
I would like to improve the reproducibility of my frequent code deployments. In other tools, you can freeze the current state to a file. 

Example:

* `pip freeze`
* `apt list --installed`
* Many more here: https://blog.shalvah.me/posts/understanding-lockfiles 

I propose a small additional command to `vcstool2` to freeze the current state. 

Proposed example command:
```bash
vcs freeze
```
This would output the current repos tracked under vcs, except for any repos that have their `version` as a `branch`, it would replace it with the commit/revision `hash`, which is globally unique. 

For example, if the user currently tracks their code like this:
```yaml
repositories:
  vcstool:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: master
  old_tools/rosinstall:
    type: svn
    url: https://github.com/vcstools/rosinstall/trunk
    version: 748
```

Then, the output of `vcs freeze` would be the following, the only difference being the version of `vcstool` is now a hash.

```yaml
repositories:
  vcstool:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: daf389377310f7f31b2171f51a79af82c31bf3e2
  old_tools/rosinstall:
    type: svn
    url: https://github.com/vcstools/rosinstall/trunk
    version: 748
```

I can then save this as an artifact with the code deployment. 

Later, when/if there is a bug in the field, it is easy for a developer to grab the stored list of repositories, and perform an exact rebuild of the deployment, even if there have been commits to the branches since then. 

Just like `pip freeze`, one can easily pipe it to a file:
`vcs freeze > ros2_frozen.repos`
