### ISSUE TITLE
Validate fails with commit hash

### ISSUE THREAD

**Issue by ppjmoors** [MaxandreOgeret/vcstool2#11]
When I use this manifest the **vcs validate** command is successful

```
repositories:
  vcstool:
    type: git
    url: https://github.com/MaxandreOgeret/vcstool2.git
    version: master
 ```
    
However, when I replace 'master' with a commit-hash: the **vcs validate** command fails.

```
=== vcstool (git) ===
Invocation of command 'validate' on client 'git' failed: UnboundLocalError: local variable 'version_type' referenced before assignment (
```
I noticed that there is also a [ticket](https://github.com/dirk-thomas/vcstool/issues/271) for this in the origina vcs tool from Dirk Thomas.

By the way: the **vcs import** command works as expected.
