### ISSUE TITLE
 vcs-import with git-repository that requires git-lfs fails in weird way (if git-lfs is not installed)  

### ISSUE THREAD

**Issue by InigoMoreno** [MaxandreOgeret/vcstool2#15]
Copy of https://github.com/dirk-thomas/vcstool/issues/237

**Comment by MaxandreOgeret** [comment]
Hey ! Thanks for the issue ! 
I cannot reproduce your problem. I dont have git lfs installed, and I have created the following repos.yaml: 

```yaml
repositories:
  pdm:
    type: git
    url: https://github.com/pdm-project/pdm.git
```

And `vcs import` gives me the following output:

```
=== ./pdm (git) ===
Cloning into '.'...
```

Also, it doesn't seem that your example repo uses lfs?

Also please post the output you get after your change.
